pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/elixir
        tags: 1.9.0-alpine
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
